version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend_service_container
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - db
      - model_service

  frontend:
    build: ./vue-frontend
    ports:
      - "3000:3000"
    container_name: frontend_service_container
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    container_name: database

  model_service:
    build:
      context: ../titanic_model_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ../titanic_model_service:/app
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

secrets:
  gitcredentials:
    file: .git-credentials
