services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend_service_container
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - model_service
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    build: ./vue-frontend
    ports:
      - "3000:3000"
    container_name: frontend_service_container
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 512M

  model_service:
    build:
      context: ../titanic_model_service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"  # Changed from 8002 to 8003 to avoid conflict
    environment:
      - FLASK_ENV=development
    volumes:
      - ../titanic_model_service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

secrets:
  gitcredentials:
    file: .git-credentials
