# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt before the rest of the files
COPY requirements.txt .

# Installing packages from req.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install pytest
RUN pip install pytest

# Copy the current directory contents into the container at /app
COPY . /app

# Expose the API port
EXPOSE 8080

# Run the FastAPI server
CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8080"]
